# Generated by Django 5.1 on 2024-08-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dados_pessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=150)),
                ('ultimo_nome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField()),
                ('estado', models.CharField(max_length=70)),
                ('bairro', models.CharField(max_length=150)),
                ('endereço', models.CharField(max_length=250)),
                ('dd_telefone', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=10)),
            ],
        ),
    ]
