# Generated by Django 5.1 on 2024-08-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_dados_pessoais_dd_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_pessoais',
            name='ddd_telefone',
            field=models.CharField(max_length=2, verbose_name='ddd'),
        ),
    ]
