# Generated by Django 5.1 on 2024-08-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_dados_pessoais_ddd_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_pessoais',
            name='ddd_telefone',
            field=models.CharField(max_length=2, verbose_name='DDD'),
        ),
    ]
