# Generated by Django 5.1 on 2024-09-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_corcar_tracaocar_alter_brand_name_alter_car_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cor_name', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TracaoCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('tracao_tipo', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
