# Generated by Django 5.1 on 2024-09-12 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_brand_name_alter_car_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cor_name', models.CharField(blank=True, null=True)),
            ],
            options={
                'ordering': ['cor_name'],
            },
        ),
        migrations.CreateModel(
            name='TracaoCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('tracao_tipo', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='cor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='car_cor', to='cars.corcar'),
        ),
        migrations.AddField(
            model_name='car',
            name='tracao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='car_tracao', to='cars.tracaocar', verbose_name='1'),
        ),
    ]
