# Generated by Django 5.1 on 2024-09-10 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_corcar_tracaocar'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='car_cor', to='cars.corcar'),
        ),
        migrations.AddField(
            model_name='car',
            name='tracao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='car_tracao', to='cars.tracaocar'),
            preserve_default=False,
        ),
    ]
